spring:
  #redis相关配置
  redis:
    database: 0
    host: 192.168.10.109
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1s
        min-idle: 0
        max-idle: 8
    timeout: 10000m